// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdRUW8UDNRxi5Vs6lmA40u9u1rMu2lII',
    appId: '1:456738383853:web:22434297ed5901de8aa9e4',
    messagingSenderId: '456738383853',
    projectId: 'space-chat-5abde',
    authDomain: 'space-chat-5abde.firebaseapp.com',
    storageBucket: 'space-chat-5abde.firebasestorage.app',
    measurementId: 'G-YJZJ27WQ74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6TK4sS6XOBoCcDWlWN6pyEnel_fyhGA',
    appId: '1:456738383853:android:2c191b6ff6d67bc68aa9e4',
    messagingSenderId: '456738383853',
    projectId: 'space-chat-5abde',
    storageBucket: 'space-chat-5abde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-W1HxVDdMjdMFCzPQghqUw3AboJKZY_Q',
    appId: '1:456738383853:ios:5b6f599496fdb1068aa9e4',
    messagingSenderId: '456738383853',
    projectId: 'space-chat-5abde',
    storageBucket: 'space-chat-5abde.firebasestorage.app',
    iosBundleId: 'com.example.spaceChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-W1HxVDdMjdMFCzPQghqUw3AboJKZY_Q',
    appId: '1:456738383853:ios:5b6f599496fdb1068aa9e4',
    messagingSenderId: '456738383853',
    projectId: 'space-chat-5abde',
    storageBucket: 'space-chat-5abde.firebasestorage.app',
    iosBundleId: 'com.example.spaceChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdRUW8UDNRxi5Vs6lmA40u9u1rMu2lII',
    appId: '1:456738383853:web:e2e7969ed437e5f78aa9e4',
    messagingSenderId: '456738383853',
    projectId: 'space-chat-5abde',
    authDomain: 'space-chat-5abde.firebaseapp.com',
    storageBucket: 'space-chat-5abde.firebasestorage.app',
    measurementId: 'G-BW5T2YM3CJ',
  );
}
